apiVersion: apps/v1
kind: Deployment
metadata:
  name: Owner
  labels:
    app: Owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Owner
  template:
    metadata:
      labels:
        app: Owner
    spec:
      containers:
        - name: Owner
          image: username/Owner:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5